"""
Abstract Base LLM Adapter interface and data models for provider-agnostic model integration.
"""

from abc import ABC, abstractmethod
from typing import AsyncGenerator, Dict, List, Optional, Any
from pydantic import BaseModel, Field


class LLMMessage(BaseModel):
    """Normalized message representation for LLM API calls."""
    role: str = Field(..., description="Message role: 'system', 'user', 'assistant', 'tool'")
    content: str = Field(..., description="Message content string")


class LLMResponse(BaseModel):
    """Normalized LLM completion response."""
    content: str = Field(..., description="Complete text output generated by the LLM")
    tokens_used: int = Field(default=0, description="Total tokens consumed (prompt + completion)")
    finish_reason: str = Field(default="stop", description="Completion finish reason")
    model_name: str = Field(default="unknown", description="Model identifier used")
    raw_response: Optional[Dict[str, Any]] = Field(default=None, description="Raw provider metadata")


class BaseLLMAdapter(ABC):
    """Abstract base adapter for all LLM providers (OpenAI, Anthropic, Gemini, Groq, OpenRouter, Ollama)."""

    def __init__(self, model_name: str, api_key: Optional[str] = None) -> None:
        self.model_name = model_name
        self.api_key = api_key

    @abstractmethod
    async def generate(
        self,
        messages: List[LLMMessage],
        temperature: float = 0.7,
        max_tokens: int = 1000,
        **kwargs: Any,
    ) -> LLMResponse:
        """Generate a complete response synchronously/non-streaming.

        Args:
            messages: List of LLMMessage prompt objects.
            temperature: Sampling temperature (0.0 to 1.0).
            max_tokens: Maximum tokens to generate.

        Returns:
            LLMResponse object.
        """
        pass

    @abstractmethod
    async def stream(
        self,
        messages: List[LLMMessage],
        temperature: float = 0.7,
        max_tokens: int = 1000,
        **kwargs: Any,
    ) -> AsyncGenerator[str, None]:
        """Stream generated response token-by-token.

        Args:
            messages: List of LLMMessage prompt objects.
            temperature: Sampling temperature.
            max_tokens: Maximum tokens to generate.

        Yields:
            Token chunks as strings.
        """
        pass
